version: "3.7"
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - securemsgredis:/data
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - securemsgpg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  securemsgredis:
  securemsgpg:
